---
- name: Services  ----  Telemetry Monitoring Stack  ----  Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ services_stack_telemetry }}"
    wait: true
    wait_timeout: 300 # seconds
  environment:
    HOSTNAME: "{{ ansible_hostname }}"
  register: output
