---
- name: Packages  ----  Install basics
  ansible.builtin.import_tasks: desktop/10-basics.yml

- name: Packages  ----  Install dev tools
  ansible.builtin.import_tasks: desktop/20-dev-tools.yml

- name: Packages  ----  Install Sublime Text
  ansible.builtin.import_tasks: desktop/21-sublime.yml

- name: Packages  ----  Install Snap packages
  ansible.builtin.import_tasks: desktop/30-snap.yml

- name: Packages  ----  Install Etcher
  ansible.builtin.import_tasks: desktop/40-etcher.yml

- name: Packages  ----  Install Chrome
  ansible.builtin.import_tasks: desktop/50-chrome.yml

- name: Packages  ----  Install Media Players
  ansible.builtin.import_tasks: desktop/60-media-players.yml

- name: Packages  ----  Uninstall unneeded packages
  ansible.builtin.import_tasks: desktop/90-uninstall.yml
