---
- name: Packages Desktop  ----  Dev Tools  ----  Ubuntu
  when: ansible_os_family == "Debian"
  block:

    - name: Packages Desktop  ----  Dev Tools  ----  Ubuntu  ---- Install apt packages
      ansible.builtin.apt:
        pkg:
          - asciidoctor
          - filezilla
          - pre-commit
          - rpi-imager
          # - yarn
        state: latest
        update_cache: true

    - name: Packages Desktop  ----  Dev Tools  ----  Ubuntu  ----  Install snap packages
      community.general.snap:
        name:
          - postman
        state: present

    - name: Packages Desktop  ----  Dev Tools  ----  Ubuntu  ----  Install Snap packages (classic)
      community.general.snap:
        name:
          - intellij-idea-ultimate
          - intellij-idea-community
        state: present
        classic: true
