---
- name: Packages Desktop  ----  Ubuntu  ----  Uninstall
  when: ansible_os_family == "Debian"
  block:

    - name: Packages Desktop  ----  Ubuntu  ----  Uninstall  ----  Pre-installed packages
      ansible.builtin.apt:
        pkg:
          - thunderbird
          - libreoffice
          - libreoffice-*
          - totem
          - totem-*
        state: absent

    - name: Packages Desktop  ----  Ubuntu  ----  Uninstall  ----  Other packages
      ansible.builtin.apt:
        pkg:
          - asciidoctor
          - yarn
          - google-chrome-stable
        state: absent

    - name: Packages Desktop  ----  Ubuntu  ----  Uninstall  ----  Pre-installed snap packages
      community.general.snap:
        name:
          - thunderbird
        state: absent

# - name: Packages Desktop  ----  Arch  ----  Uninstall
#   when: ansible_os_family == "Archlinux"
#   block:

    # todo ...
